### ISSUE TITLE
yunohost backup create command give me an error

### ISSUE THREAD

**Issue by M5oul** [YunoHost/moulinette-yunohost#69] opened 2015-06-21 19:53 UTC
```bash
yunohost backup create
Traceback (most recent call last):
  File "/usr/bin/yunohost", line 160, in <module>
    print_json=PRINT_JSON, use_cache=USE_CACHE)
  File "/usr/lib/python2.7/dist-packages/moulinette/__init__.py", line 117, in cli
    moulinette.run(args, print_json)
  File "/usr/lib/python2.7/dist-packages/moulinette/interfaces/cli.py", line 197, in run
    ret = self.actionsmap.process(args, timeout=5)
  File "/usr/lib/python2.7/dist-packages/moulinette/actionsmap.py", line 458, in process
    return func(**arguments)
  File "/usr/lib/moulinette/yunohost/backup.py", line 68, in backup_create
    if name in backup_list()['archives']:
  File "/usr/lib/moulinette/yunohost/backup.py", line 300, in backup_list
    archives = os.listdir(archives_path)
OSError: [Errno 2] No such file or directory: '/home/yunohost.backup/archives'
```

**Comment by jeromelebleu** [comment] 2015-06-22 08:00
Duplicate of https://github.com/YunoHost/moulinette-yunohost/issues/65.

It has been fixed but not released yet, coming soon!

**Closed by jeromelebleu** 2015-06-22 08:00 UTC
